

import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Menu from "./menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
       <div>
        <Menu />
        <div className=" absolute left-[1600px] top-5">
          <Link href="/">지갑</Link>
        </div>
        </div>
        {children}
        
      </body>
    </html>
  );
}
