

import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Menu from './headermenu/page'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className} >
        <>
        <div >
          <div className='flex flex-col font-semibold 
        text-lg '>
        <Menu/>
          </div>
        </div>
        {children}
        </>
      </body>
    </html>
  );
}
