import Link from 'next/link'
import LoginForm from './loginform'
import Menu from './headermenu/page'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <>
        <div >
          <div className='flex flex-col font-semibold 
        text-lg '>
        <Menu/>
          </div>
        </div>
        
        {/* <div className=' top-5 left-52'>
        <Link href='/'>
          <img src='/Logo.png' className='w-20'/>
        </Link>
        </div> */}

        </>
        {children}</body>
    </html>
  )
}
